-- Orari prenotabili
CREATE TABLE availability_slot (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date  DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time   TIME NOT NULL,
    CONSTRAINT uk_availability_slot_date_time UNIQUE (slot_date, start_time)
);

-- Prenotazioni dei clienti
CREATE TABLE booking (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id          BIGINT       NOT NULL REFERENCES availability_slot (id),
    name             VARCHAR(80)  NOT NULL,
    email            VARCHAR(254) NOT NULL,
    phone            VARCHAR(30)  NOT NULL,
    tattoo_idea      VARCHAR(1000) NOT NULL,
    placement        VARCHAR(120) NOT NULL,
    approximate_size VARCHAR(120) NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    -- Un orario può avere una sola prenotazione: il database blocca i doppioni
    -- anche se due clienti confermano nello stesso istante.
    CONSTRAINT uk_booking_slot UNIQUE (slot_id)
);
